apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web-app

resources:
- 3-web-application/k8s/app-configmap.yaml
- 3-web-application/k8s/app-secret.yaml
- 3-web-application/k8s/app-deployment.yaml
- 3-web-application/k8s/app-service.yaml
- 4-advanced/ingress/ingress.yaml

commonLabels:
  app: web-app
  project: kubernetes-hands-on

replicas:
- name: web-app-deployment
  count: 3